### PR TITLE
Improvements in tank_facts_announce and score_difference

### PR DESCRIPTION
**Pull request by vikingo12**
thanks to Forgetest!!!!!!!!!!!!!!!!!!!! 😃😃😃😃😃

### CODE REVIEW

**Comment by jensewe** [comment]
Presonally dislike the translation changes, sort of getting unaligned because of `-es` and `-s`. Anyway the translations here are just for demostrations which users can easily modify at their wills.

Would be better if you can make `l4d2_score_difference` translation-supported as well :)

**Comment by vikingo12** [comment]
> Presonally dislike the translation changes, sort of getting unaligned because of `-es` and `-s`. Anyway the translations here are just for demostrations which users can easily modify at their wills.
> 
> Would be better if you can make `l4d2_score_difference` translation-supported as well :)

es and s are more logical, for example Punch:10 doesn't seem so fitting

**Comment by jensewe** [comment]
Let's say 1 or 0 punch? :D 
Not being a native speaker, nor even a fan of linguistics, but plural is really something I'm not gonna be happy with.

**Comment by vikingo12** [comment]
> Let's say 1 or 0 punch? :D Not being a native speaker, nor even a fan of linguistics, but plural is really something I'm not gonna be happy with.

Ok, have it ur way then

**Pull request merged**
